//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompliantFile
    {
        public int ID { get; set; }
        public string ComplaintFilePath { get; set; }
        public Nullable<int> ComplaintId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Complaint Complaint { get; set; }
    }
}
